game/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game_functionality.urls'))
]

game_functionality/urls.py
from django.urls import path
from . import views

app_name = 'game_functionality'

urlpatterns = [

    path('', views.index, name='index')

]

game_functionality/models.py
from django.db import models

# Create your models here.

game_functionality/views.py
from django.shortcuts import render
from .utils import Game


def index(request):
    game_id = request.session.get('game_id', False)
    game = Game()
    x_or_o = request.session.get('x_or_o', False)
    if request.method == 'POST':
        count = 0
        if game_id:
            print(x_or_o)
            #if game.check_draw(game_id):
            if x_or_o == 'x':
                game.load_file(game_id, int(request.POST['btn']), x_or_o)
                game.check_game(game_id)
                x_or_o = request.session['x_or_o'] = 'o'
                print('xorx = x')
            else:
                print(x_or_o)
                game.load_file(game_id, int(request.POST['btn']), x_or_o)
                game.check_game(game_id)
                x_or_o = request.session['x_or_o'] = 'x'
                print('x_oro = 000000')
            # else:
            #     print('vews draw')
    else:

        request.session['game_id'] = game.id
        request.session['x_or_o'] = 'x'
        game.create_file(game.id)
    return render(request, 'index.html')
# def index(request):
#     x_or_o = 'x'
#
#     game_id = request.session.get('game_id', False)
#     game = Game()
#
#
#     if request.method == 'POST':
#         if game_id:
#             if x_or_o == 'x':
#
#                 print('pox-0')
#                 pos_x_o = game.load_file(game_id)
#                 #pos_x_o[int(request.POST['btn'])-1] = 'x'
#                 #print(request.POST['btn'])
#                 x_or_o = 'o'
#                 print(pos_x_o)
#             else:
#
#                 pos_x_o = game.load_file(game_id)
#                 pos_x_o[int(request.POST['btn'])-1] = 'o'
#                 print(request.POST['btn'])
#                 x_or_o = 'x'
#                 print(pos_x_o)
#         else:
#             print('creqat new file')
#             game.create_file(game_id)
#             request.session['game_id'] = game.id
#
#
#             print(request. session['game_id'])
#     return render(request, 'index.html')








#http: // qaru.site / questions / 1068600 / ajax - post - in -django - framework
#https://stackoverflow.com/questions/13465711/how-do-i-post-with-jquery-ajax-in-django

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
.button {
  background-color: #4CAF50; /* Green */
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
}

.button1 {background-color: #f44336;} /* Red */
.button2 {background-color: #555555;} /* Black */
</style>



</head>
<body>


<div id ="box">
<form action="{% url 'game_functionality:index' %}" method="post" >
{% csrf_token %}
{% for i in i|rjust:9 %}


    <input type="submit" name="btn" value="{{ forloop.counter }}"  onclick=" clickBtn('btn1')"/>
    {% if forloop.counter|divisibleby:3 %}
       </br>
    {% endif %}

{% endfor %}
</form>
<!--<input type="button" id ="btn2" onclick=" clickBtn('btn2')"/>-->
<!--<input type="button" id ="btn3" onclick=" clickBtn('btn3')"/></br>-->
<!--<input type="button" id ="btn4" onclick=" clickBtn('btn4')"/>-->
<!--<input type="button" id ="btn5" onclick=" clickBtn('btn5')"/>-->
<!--<input type="button" id ="btn6" onclick=" clickBtn('btn6')"/></br>-->
<!--<input type="button" id ="btn7" onclick=" clickBtn('btn7')"/>-->
<!--<input type="button" id ="btn8" onclick=" clickBtn('btn8')"/>-->
<!--<input type="button" id ="btn9" onclick=" clickBtn('btn9')"/>-->

</form>
</div>


</body>
</html>